### Homework 4 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [22]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [2]:
import numpy as np

#dir(np.array)
#dir(car)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__name__',
 '__ne__',
 '__new__',
 '__qualname__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__self__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__text_signature__']

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [23]:
headers = ([car.dtype], [mpg.dtype], [horsepower.dtype], [origin.dtype])
print(headers)

([dtype('O')], [dtype('float64')], [dtype('float64')], [dtype('O')])


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
alias
instead of typing out numpy you can just type out np

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [107]:
import numpy as np

headers.ndim
print(headers.ndim)

1


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [3]:
#np.multiply(mpg, 12)
#np.divide(mpg, 3)
#np.power(mpg, 4)
#np.sqrt(mpg)

NameError: name 'mpg' is not defined

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [135]:
np.median(horsepower)
np.sum(horsepower)
np.min(horsepower)
horsepower.max(axis=0)

# for mode
vals,counts = np.unique(horsepower, returns_counts = TRUE)
index = np.argmax(counts)
vals[index]

230.0

7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [161]:
acceleration[0:5]
acceleration[::2]

array([12. , 11.5, 11. , 12. , 10.5])

8. Show how to select the number `99` in the array below. 

In [5]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [6]:
select_99[1, 2]

99

9. Select the last element in each subarray (do this with one operation.)

In [7]:

select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [11]:
select_more[:,2]

array([3, 6, 9])

10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [153]:
np.log(mpg)

array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [156]:
np.unique(origin)

array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [15]:
temp = [[72,93,97,91], [70,88,91,79], [45,36,36,32], [30,30,42,33]]
import numpy as np
np_temp = np.array(temp)
print(np_temp.ndim)
print(np_temp.shape)

temp_3d_array = np.array([[[72,93,97,91], [70,88,91,79], [45,36,36,32], [30,30,42,33]]])
print(temp_3d_array.ndim)
print(temp_3d_array.shape)

a = np.array([[[72,93,97,91], [70,88,91,79], [45,36,36,32], [30,30,42,33]]])
a = np.expand_dims(a, axis = 0)
a = np.repeat(a,4,axis = 0)
print(a.ndim)
print(a.shape)




2
(4, 4)
3
(1, 4, 4)
4
(4, 1, 4, 4)


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [24]:
x = (origin == 'US')
print(x)

[ True  True  True  True  True  True  True  True  True  True False  True
  True  True  True  True  True  True  True  True False  True  True  True
 False False False False False False  True  True  True  True  True False
  True False  True False  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True False False False
 False False False  True False  True False  True  True  True  True  True
  True  True  True  True  True  True False  True  True  True  True False
 False False False  True False False  True False  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True False  True  True  True  True  True False  True False False  True
  True False  True  True False False False False  True False False  True
  True  True  True  True False  True False  True  True  True  True  True
  True  True  True  True False False False False False  True False False
 False False False  True  True  True  True  True  T

14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [25]:
car[origin == 'US']

array(['Chevrolet Chevelle Malibu', 'Buick Skylark 320',
       'Plymouth Satellite', 'AMC Rebel SST', 'Ford Torino',
       'Ford Galaxie 500', 'Chevrolet Impala', 'Plymouth Fury iii',
       'Pontiac Catalina', 'AMC Ambassador DPL',
       'Chevrolet Chevelle Concours (sw)', 'Ford Torino (sw)',
       'Plymouth Satellite (sw)', 'AMC Rebel SST (sw)',
       'Dodge Challenger SE', "Plymouth 'Cuda 340",
       'Ford Mustang Boss 302', 'Chevrolet Monte Carlo',
       'Buick Estate Wagon (sw)', 'Plymouth Duster', 'AMC Hornet',
       'Ford Maverick', 'AMC Gremlin', 'Ford F250', 'Chevy C20',
       'Dodge D200', 'Hi 1200D', 'Chevrolet Vega 2300', 'Ford Pinto',
       'AMC Gremlin', 'Plymouth Satellite Custom',
       'Chevrolet Chevelle Malibu', 'Ford Torino 500', 'AMC Matador',
       'Chevrolet Impala', 'Pontiac Catalina Brougham',
       'Ford Galaxie 500', 'Plymouth Fury iii', 'Dodge Monaco (sw)',
       'Ford Country Squire (sw)', 'Pontiac Safari (sw)',
       'AMC Hornet Sportabout (

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

2. Transpose the following array. 

In [ ]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

5. On average are Japanse cars more fuel efficient than US cars? 

6. What is the correlation coefficient of `mpg` and `weight`?

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 